-- ROLLBACK de 004. Devuelve exactamente los permisos que habia antes.

GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_festival_pre_dedup_v3" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_kardex_2026_legacy_20260731" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_registro_de_inscripcion_2026_20260430_230827" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_registro_kardex_2026_20260430_230827" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_registro_solicitud_2026_20260430_230827" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_cartas_invitacion_2026" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_contactos_global_Obsoleto" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_festival_contactos_global" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_historial_participaciones" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_instituciones" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_pagos_2026" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_participantes_2024" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_participantes_2025" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_recepcion_notas_2024" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_recepcion_notas_2025" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_registro_de_inscripcion_2024" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_registro_de_inscripcion_2025" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_registro_de_inscripcion_2026" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_registro_kardex_2026" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_registro_solicitud_2024" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_registro_solicitud_2025" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_registro_solicitud_2026" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_representantes" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_backup_zamorano_20260806_solicitantes" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."_merge_log" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."agente_ubicaciones" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."agentes" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."agrupacion_credenciales" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."bandeja_etiquetas" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."bandeja_etiquetas_conversacion" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."bot_config" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."bot_message_buffer" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."bot_reglas" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."cartas_invitacion_2025_legacy" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."compromisos_credenciales_2026" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."config_entradas_2026" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."cupones_2026" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."documents" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."entradas_2026" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."etiquetas_entradas_2026" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."festival_contactos_global" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."historial_participaciones" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."inscripcion_multimedia_estado" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."multimedia" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."n8n_chat_histories" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."notificaciones_usuario" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."plan_rutas" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."plan_rutas_paradas" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."plantillas_meta" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."recibos_emitidos" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."registro_visitas" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."rutas_colegios" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."ycloud_eventos_log" TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON public."zonas" TO anon, authenticated;
GRANT SELECT ON public."_backup_festival_pre_dedup_v3" TO anon, authenticated;
GRANT SELECT ON public."_backup_kardex_2026_legacy_20260731" TO anon, authenticated;
GRANT SELECT ON public."_backup_registro_de_inscripcion_2026_20260430_230827" TO anon, authenticated;
GRANT SELECT ON public."_backup_registro_kardex_2026_20260430_230827" TO anon, authenticated;
GRANT SELECT ON public."_backup_registro_solicitud_2026_20260430_230827" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_cartas_invitacion_2026" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_contactos_global_Obsoleto" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_festival_contactos_global" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_historial_participaciones" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_instituciones" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_pagos_2026" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_participantes_2024" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_participantes_2025" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_recepcion_notas_2024" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_recepcion_notas_2025" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_registro_de_inscripcion_2024" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_registro_de_inscripcion_2025" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_registro_de_inscripcion_2026" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_registro_kardex_2026" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_registro_solicitud_2024" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_registro_solicitud_2025" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_registro_solicitud_2026" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_representantes" TO anon, authenticated;
GRANT SELECT ON public."_backup_zamorano_20260806_solicitantes" TO anon, authenticated;
GRANT SELECT ON public."_merge_log" TO anon, authenticated;
GRANT SELECT ON public."agentes" TO anon, authenticated;
GRANT SELECT ON public."agrupacion_credenciales" TO anon, authenticated;
GRANT SELECT ON public."bandeja_etiquetas" TO anon, authenticated;
GRANT SELECT ON public."bandeja_etiquetas_conversacion" TO anon, authenticated;
GRANT SELECT ON public."bot_config" TO anon, authenticated;
GRANT SELECT ON public."bot_message_buffer" TO anon, authenticated;
GRANT SELECT ON public."bot_reglas" TO anon, authenticated;
GRANT SELECT ON public."cartas_invitacion_2025_legacy" TO anon, authenticated;
GRANT SELECT ON public."compromisos_credenciales_2026" TO anon, authenticated;
GRANT SELECT ON public."config_entradas_2026" TO anon, authenticated;
GRANT SELECT ON public."crm_contactos" TO anon, authenticated;
GRANT SELECT ON public."cupones_2026" TO anon, authenticated;
GRANT SELECT ON public."deudas_2026" TO anon, authenticated;
GRANT SELECT ON public."documents" TO anon, authenticated;
GRANT SELECT ON public."festival_contactos_global" TO anon, authenticated;
GRANT SELECT ON public."historial_participaciones" TO anon, authenticated;
GRANT SELECT ON public."inscripcion_multimedia_estado" TO anon, authenticated;
GRANT SELECT ON public."multimedia" TO anon, authenticated;
GRANT SELECT ON public."n8n_chat_histories" TO anon, authenticated;
GRANT SELECT ON public."notificaciones_usuario" TO anon, authenticated;
GRANT SELECT ON public."pagos_2025_normalized" TO anon, authenticated;
GRANT SELECT ON public."pagos_2026_normalized" TO anon, authenticated;
GRANT SELECT ON public."pagos_historial_all" TO anon, authenticated;
GRANT SELECT ON public."plantillas_meta" TO anon, authenticated;
GRANT SELECT ON public."recibos_emitidos" TO anon, authenticated;
GRANT SELECT ON public."registro_visitas" TO anon, authenticated;
GRANT SELECT ON public."v_campanas_dashboard" TO anon, authenticated;
GRANT SELECT ON public."v_carnets_validos" TO anon, authenticated;
GRANT SELECT ON public."v_envios_pendientes" TO anon, authenticated;
GRANT SELECT ON public."vimeo_fb_progreso" TO anon, authenticated;
GRANT SELECT ON public."ycloud_eventos_log" TO anon, authenticated;
GRANT SELECT ON public."zonas" TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.marcar_membresia_paquete_2026(p_owner_id text, p_origen text, p_id_kardex text, p_id_contacto text, p_order_id bigint, p_monto numeric) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.marcar_membresia_videos_2026(p_owner_id text, p_origen text, p_id_kardex text, p_id_contacto text, p_order_id bigint, p_monto numeric) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.marcar_membresia_pagada(p_id_kardex text, p_order_id bigint, p_monto numeric) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.marcar_membresia_paquete_pagada(p_id_kardex text, p_order_id bigint, p_monto numeric) TO PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated;
